package com.cst438.controller;

import com.cst438.domain.*;
import com.cst438.dto.EnrollmentDTO;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Optional;

@RestController
@CrossOrigin(origins = "http://localhost:3000")
public class StudentController {


   // student gets transcript
   // list course_id, sec_id, title, credit, grade in chronological order
   // user must be student
   // studentId will be temporary until Login security is implemented
   @GetMapping("/transcript")
   public List<EnrollmentDTO> getTranscript(@RequestParam("studentId") Optional<Integer> studentId) {

       // TODO remove the following line when done

       return null;
   }

    // student gets class schedule for a given term
    // user must be student
    // remove studentId request param after login security implemented
   @GetMapping("/enrollment")
   public List<EnrollmentDTO> getSchedule(
           @RequestParam("year") int year,
           @RequestParam("semester") String semester,
           @RequestParam("studentId") int studentId) {


     // TODO remove the following line when done

       return null;
   }


    // student adds enrollment into a section
    // user must be student
    //  check that today is between addStartDate and addDeadline for section
    // return EnrollmentDTO with enrollmentId generated by database
    @PostMapping("/enrollment")
    public EnrollmentDTO addCourse(@RequestBody EnrollmentDTO dto) {

        // TODO remove the following line when done

        return null;

    }

    // student drops a course
    // user must be student
    //  check that today is before dropDeadline for section
   @DeleteMapping("/enrollment/{enrollmentId}")
   public void dropCourse(@PathVariable("enrollmentId") int enrollmentId) {

       // TODO
   }
}